on: push
jobs:
  build-apk:
    name: build-apk
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
    # - name: setup Flutter
    #   uses: subosito/flutter-action@v2.16.0
    #   with: 
    #     channel: stable
    #     flutter-version: 3.24.3
    - run: cd engineer_helper
    - run: ls
    # - name: get flutter packages
    #   run: flutter pub get
    # - name: start building apk!
    #   run: flutter build apk