on: push
jobs:
  build-apk:
    name: build-apk
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
    - name: setup Flutter
      uses: subosito/flutter-action@v2.16.0
      with: 
        channel: stable
        flutter-version: 3.24.3
    - name: get flutter packages
      working-directory: ./engineer_helper
      run: flutter pub get
    - name: start building apk!
      working-directory: ./engineer_helper
      run: flutter build apk