on: push
jobs:
  build-apk:
    name: build-apk
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
    - name: Flutter action
      uses: subosito/flutter-action@v2.16.0
      with: 
        channel: stable
        flutter-version: 4.0.0
    - run: cd ./engineer_helper
    - name: get flutter packages
      run: flutter pub get
    - name: start building apk!
      run: flutter build apk