on: push
jobs:
  build-apk:
    name: build-apk
    runs-on: ubuntu-latest
    steps:
    - name: clone
      uses: actions/checkout@v4
      with: 
        channel: stable
        flutter-version: 3.19.0
    - run: flutter --version
  